[package]
name = "rust_reachability_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.75", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
tempfile = "3.12"
uuid = { version = "1.10.0", features = ["v4"] }

