[package]
name = "rust_reachability_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.75", features = ["full"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
tempfile = "3.2"
serde_json = "1.0"
clap = "4.5.16"
colored = "2.0.0"

